# Generated by Django 3.2.5 on 2021-08-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('boatLicenseNumber', models.CharField(max_length=255)),
                ('insuranceNumber', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=1025)),
                ('siretNumber', models.IntegerField()),
                ('tradeRegisterNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('idPage', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('comment', models.CharField(1023)),
                ('size', models.DecimalField(decimal_places=1)),
                ('weight', models.DecimalField(decimal_places=3)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('released', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='fishingdate.user')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('idBoat', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('brand', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('URLBoat', models.CharField(max_length=255)),
                ('boatLicenseType', models.CharField(max_length=255)),
                ('boatType', models.CharField(max_length=255)),
                ('equipments', models.CharField(max_length=255)),
                ('deposit', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('bedsNumber', models.IntegerField()),
                ('harbor', models.CharField(max_length=255)),
                ('longitude', models.DecimalField()),
                ('latitude', models.DecimalField()),
                ('motor', models.CharField(max_length=255)),
                ('horsepower', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boatsList', to='fishingdate.user')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('idExcursion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursionTitle', models.CharField(max_length=255)),
                ('information', models.CharField(max_length=1023)),
                ('excursionType', models.CharField(max_length=255)),
                ('tariff', models.CharField(max_length=255)),
                ('numberOfPassengers', models.IntegerField()),
                ('excursionPrice', models.DecimalField(decimal_places=2)),
                ('idOwner', models.IntegerField()),
                ('idBoat', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishingExcursionsList', to='fishingdate.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('idBooking', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idExcursion', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('nbBookedSeats', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2)),
                ('idBooker', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingsList', to='fishingdate.user')),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeList',
            fields=[
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateTimeList', to='fishingdate.user.excursion'))
            ]
        )
    ]
